#!/bin/bash
#SBATCH -n 1
#SBATCH --mem=10G
#SBATCH -p mpi
#SBATCH -t 4:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

module load matlab/2016b
cnmfepath="${HOME}/code/CNMF_E"
grinpath="${HOME}/code/grin-analysis"
matlab -r "addpath(genpath('${grinpath}')); addpath(genpath('${cnmfepath}')); batch_cnmfe('$1');"
