#!/bin/bash
#SBATCH -n 1
#SBATCH -c 1
#SBATCH --mem=15G
#SBATCH -p mpi
#SBATCH -t 9:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# this is the main batch script that runs cnmfe to extract neurons
# for a 30 min recording w/~270x312px resolution, it takes about 2 hours

module load matlab/2016b
cnmfepath="${HOME}/code/cnmfe_old"
grinpath="${HOME}/code/grin-analysis"
echo "$(pwd)"
echo "Running for $1"
matlab -r "addpath(genpath('${grinpath}')); addpath(genpath('${cnmfepath}')); batch_cnmfe('$1');"
