#!/bin/bash
#SBATCH -n 2
#SBATCH --mem=20G
#SBATCH -p interactive
#SBATCH --pty
#SBATCH -t 8:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# use cnmfe to extract neurons from a dataset
# this assumes you are using the new version of CNMF_E

codepath="${HOME}/code"
module unload matlab/2016b
module load matlab/2017b
matgraph -r "addpath(genpath('${code}')); cnmfe_correlation_bounds('$1'); exit"
