#!/bin/bash
#SBATCH -c 1
#SBATCH -n 1
#SBATCH --mem=70G
#SBATCH -p medium
#SBATCH -t 2-0:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# use cnmfe to extract neurons from a dataset
# this assumes you are using the new version of CNMF_E
# the config file is executable by the shell and can be added into the
# extract function to customize threshold levels

codepath="${HOME}/code"
module unload matlab/2016b
module load matlab/2017b
if [ -f cnmfe.config ]; then
  . ./cnmfe.config
	#matlab -singleCompThread -r "addpath(genpath('${code}')); parpool('local', 3); cnmfe_extract('$1', $spatial, $temporal, $min_corr, $min_pnr);"
	matlab -singleCompThread -r "addpath(genpath('${codepath}')); cnmfe_extract('$1', $spatial, $temporal, $min_corr, $min_pnr);"
else
	#matlab -singleCompThread -r "addpath(genpath('${code}')); parpool('local', 3); cnmfe_extract('$1');"
	matlab -singleCompThread -r "addpath(genpath('${codepath}')); cnmfe_extract('$1');"
fi
