#!/bin/bash
#SBATCH -c 2
#SBATCH -n 2
#SBATCH --mem=130G
#SBATCH -p short
#SBATCH -t 12:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# use cnmfe to extract neurons from a dataset
# this assumes you are using the new version of CNMF_E
# the config file is executable by the shell and can be added into the
# extract function to customize threshold levels

cnmfe="${HOME}/code/cnmfe-old"
grin="${HOME}/code/grin-analysis"
module unload matlab/2016b
module load matlab/2017b
matlab -r "addpath(genpath('${cnmfe}')); addpath(genpath('${grin}')); cnmfe_extract('$1');"
