#!/bin/bash
#SBATCH -n 6
#SBATCH --mem=45G
#SBATCH -p priority
#SBATCH -t 8:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# use cnmfe to extract neurons from a dataset
# this assumes you are using the new version of CNMF_E

codepath="${HOME}/code"
module unload matlab/2016b
module load matlab/2017b
if [ -f cnmfe.config ]; then
  . ./cnmfe.config
  matlab -r "addpath(genpath('${code}')); cnmfe_extract('$1', $spatial, $temporal, $min_corr, $min_pnr);"
else
  matlab -r "addpath(genpath('${code}')); cnmfe_extract('$1');"
fi
