#!/bin/bash
#SBATCH -n 2
#SBATCH --mem=16G
#SBATCH -p short
#SBATCH -t 12:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# downsample the tif data and memmap it
module unload matlab/2016b
module load matlab/2017a
codepath="${HOME}/code"

matlab -r "addpath(genpath('${codepath}')); memmap_file_sequence('.', '$1', 4);"
