#!/bin/bash
#SBATCH -c 1
#SBATCH -n 1
#SBATCH --mem=20G
#SBATCH -p short
#SBATCH -t 2:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

module load matlab/2017b
codepath="${HOME}/code"

matlab -singleCompThread -r "addpath(genpath('${codepath}')); compute_correlations('$1');"
