#!/bin/bash

# first motion correct the mat recording, then run old batch-extract on it
set -e

set -e

srun -n 1 -c 5 --mem=40G -p short -t 8:00:00 batch-motion-correct $1

motion="motion-corrected-${1}"
sbatch /home/wg41/code/grin-analysis/batch-extract-old $motion
