#!/bin/bash
#SBATCH -c 1
#SBATCH --mem=20G
#SBATCH -p short
#SBATCH -t 6:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=wgillis@g.harvard.edu

# makes a max projection, avg projection, and dff image for anatomical analysis

codepath="${HOME}/code"
module unload matlab/2016b
module load matlab/2017b
matlab -r "addpath(genpath('${code}')); mat2avi('$1', '$1'); exit;"
ffmpeg -i "$1.avi" "$1.mp4"
